name: Generate PDF from Markdown

on:
  push:
    branches:
      - main  # Change to your default branch if it's not main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y pandoc texlive texlive-xetex

    - name: Generate PDF
      run: |
        mkdir -p public
        pandoc -s -o public/manual.pdf $(find . -name '*.md' | sort)

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
        publish_branch: gh-pages  # Ensure this matches your GitHub Pages branch
