# .github/workflows/convert-to-pdf.yml

name: Docs to PDF

on:
  push:
    branches: [ main ]
  paths:
    - 'docs/**.md'  # Trigger workflow on changes to markdown files in the docs folder

jobs:
  converttopdf:
    name: Build PDF
    runs-on: ubuntu-latest  # You can choose a different runner

    steps:
      - uses: actions/checkout@v3  # Checkout the code

      - uses: baileyjm02/markdown-to-pdf@v1  # Use the markdown-to-pdf action
        with:
          input_dir: docs  # Path to the folder containing markdown files
          output_dir: pdfs  # Output directory for the generated PDF (in the public folder)
          images_dir: docs/images  # Path to the folder containing images (if applicable)
          image_import: ./images  # How image paths should be adjusted (optional)
